---
- hosts: localhost
  connection: local
  tasks:
  - name: MySQL | Make sure the MySQL packages are installed
    apt: pkg=mysql-server,python3-mysqldb update_cache=yes
    when: ansible_os_family == "Debian"

  - name: MySQL | Make sure the MySQL packages are installed
    apt: pkg=python3-pymysql
    when: ansible_os_family == "Debian"
    ignore_errors: yes
    
  - name: MySQL | Make sure the MySQL packages are installed
    yum: name=mariadb-server,MySQL-python
    when: ansible_os_family == "RedHat"
