---
- hosts: localhost
  connection: local
  vars:
    docker_bridge_ip: "172.0.17.1"
  roles:
    - role: indigo-dc.consul
      consul_mode: "agent"
      consul_servers: "{{ consul_server_ips }}"

    - role: indigo-dc.marathon-lb
      marathon_lb_auth_creds: "{{marathon_username}}:{{marathon_password}}"
