---
- hosts: localhost
  connection: local
  vars:
    - docker_bridge_ip: "172.0.17.1"
  roles:
    - role: indigo-dc.consul
      consul_mode: "server"
      consul_servers: "{{ mesos_masters_list_ips }}"

    - role: indigo-dc.zookeeper
      zookeeper_host_list: "{{ mesos_masters_list_ips }}"

    - role: indigo-dc.mesos
      mesos_install_mode: "master"
      zookeeper_peers: "{{ mesos_masters_list_ips }}"
      mesos_masters_list: "{{ mesos_masters_list_ips }}"

    - role: indigo-dc.marathon
      zookeeper_peers: "{{ mesos_masters_list_ips }}"
      marathon_username: "{{ marathon_user }}"
      marathon_password: "{{ marathon_pass }}"
   
    - role: indigo-dc.chronos
      zookeeper_peers: "{{ mesos_masters_list_ips }}"
      chronos_username: "{{ chronos_user }}"
      chronos_password: "{{ chronos_pass }}"
   
