---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
     slurm_front_end_ip: '{{ ansible_default_ipv4.address }}'
  pre_tasks:
  - name: "Add nodes mapping in hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item.1 }}.*$' line="{{ item.1 }} {{ vnode_prefix }}{{ item.0 + 1 }} {{ vnode_prefix }}{{ item.0 + 1 }}.localdomain" state=present
    with_indexed_items: '{{ wn_ips }}'
  - name: "Add master mapping in hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ front_end_ip }}.*$' line="{{ front_end_ip }} slurmserver slurmserver.localdomain" state=present
  roles:
  - role: indigo-dc.nfs
    nfs_mode: 'server'
    nfs_exports: [{path: "/home", export: "{{ vnode_prefix }}*.localdomain(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"}]
  - role: indigo-dc.slurm
    slurm_type_of_node: 'front'
    slurm_wn_ips: '{{ wn_ips }}'
    slurm_vnode_prefix: '{{ vnode_prefix }}'
