---
- hosts: localhost
  connection: local
  vars:
     vnode_prefix: vnode-
  pre_tasks:
  - name: Create dir for the NFS PV
    file: path=/pv state=directory mode=755
  - name: Create auth file dir
    file: path=/etc/kubernetes/pki state=directory mode=755 recurse=yes
  - name: Create auth data file with an admin user
    copy: content='{{kube_admin_token}},{{kube_admin_username}},100,"users,system:masters"' dest=/etc/kubernetes/pki/auth mode=600

  roles:
  - role: indigo-dc.openvpn
    openvpn_type_of_node: 'front'
    openvpn_frontname: 'kubeserver'
    when: fe_hybrid_cluster
  - role: indigo-dc.nfs
    nfs_mode: 'server'
    nfs_exports: [{path: "/pv", export: "{{ vnode_prefix }}*.localdomain(fsid=0,rw,async,no_root_squash,no_subtree_check,insecure)"}]
  - role: grycap.kubernetes
    kube_server: '{{ kube_front_end_ip }}'
    kube_api_server: '{{ kube_front_end_ip }}'
    kube_apiserver_options: [{option: "--service-node-port-range", value: "8000-35000"}, {option: "--insecure-port", value: "8080"}, {option: "--token-auth-file", value: "/etc/kubernetes/pki/auth"}]
    kube_deploy_dashboard: true
