---
- hosts: localhost
  connection: local
  roles:
  - role: grycap.im
    when: enabled|bool and clues_powermanager_plugin == "im"
  - role: indigo-dc.clues
    indigo_orchestrator_url: "{{ orchestrator_url }}"
    when: enabled|bool
